# Generated by Django 5.0.14 on 2026-09-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, unique=True, verbose_name='Hudud nomi')),
                ('nomi_kiril', models.CharField(blank=True, help_text="Manba fayldagi asl ko'rinishi", max_length=255, verbose_name='Hudud nomi (kirill)')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='IjtimoiyHolatTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.SlugField(max_length=80, unique=True, verbose_name='Kod')),
                ('nomi', models.CharField(max_length=255, verbose_name='Ijtimoiy holat belgisi')),
                ('nomi_kiril', models.CharField(blank=True, max_length=255, verbose_name='Ijtimoiy holat belgisi (kirill)')),
                ('tartib', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Ijtimoiy holat turi',
                'verbose_name_plural': 'Ijtimoiy holat turlari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='IjtimoiyToifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, unique=True, verbose_name='Toifa nomi')),
                ('nomi_kiril', models.CharField(blank=True, max_length=255, verbose_name='Toifa nomi (kirill)')),
            ],
            options={
                'verbose_name': 'Ijtimoiy toifa',
                'verbose_name_plural': 'Ijtimoiy toifalar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='MuammoToifasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, unique=True, verbose_name='Muammo toifasi')),
                ('nomi_kiril', models.CharField(blank=True, max_length=255, verbose_name='Muammo toifasi (kirill)')),
            ],
            options={
                'verbose_name': 'Muammo toifasi',
                'verbose_name_plural': 'Muammo toifalari',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodi', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='MFY kodi')),
                ('nomi', models.CharField(db_index=True, max_length=255, verbose_name='MFY nomi')),
                ('nomi_kiril', models.CharField(blank=True, help_text="Manba fayldagi asl ko'rinishi", max_length=255, verbose_name='MFY nomi (kirill)')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mahallalar', to='registry.hudud', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Mahalla (MFY)',
                'verbose_name_plural': 'Mahallalar (MFY)',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Oila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unikal_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Oila unikal ID')),
                ('azolari_soni', models.PositiveSmallIntegerField(blank=True, help_text="Manba faylda ko'rsatilgan son", null=True, verbose_name="Oila a'zolari soni")),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilalar', to='registry.mahalla', verbose_name='Mahalla')),
            ],
            options={
                'verbose_name': 'Oila',
                'verbose_name_plural': 'Oilalar',
                'ordering': ['unikal_id'],
            },
        ),
        migrations.CreateModel(
            name='Shaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib_raqami', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Manba fayldagi tartib raqami')),
                ('asosiy_arizachi', models.BooleanField(default=False, verbose_name='Asosiy arizachi')),
                ('fio', models.CharField(db_index=True, max_length=255, verbose_name='F.I.O.')),
                ('fio_kiril', models.CharField(blank=True, help_text='Manba fayldagi asl yozuv (kirill yoki nuqsonli kodirovka bilan)', max_length=255, verbose_name="F.I.O. (manbadagi ko'rinishi)")),
                ('jshshir', models.CharField(blank=True, db_index=True, help_text='14 xonali shaxsiy identifikatsiya raqami', max_length=20, verbose_name='JSHSHIR')),
                ('takroriy_jshshir', models.BooleanField(db_index=True, default=False, help_text='Manba faylda bu JSHSHIR bir necha qatorda uchraydi - tekshirish talab etiladi', verbose_name='JSHSHIR takrorlangan')),
                ('jinsi', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], db_index=True, max_length=10, verbose_name='Jinsi')),
                ('tugilgan_sana', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('yoshi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Yoshi')),
                ('reestrdan_chiqqan', models.BooleanField(default=False, verbose_name="O'z arizasiga ko'ra ijtimoiy reestrdan chiqqan")),
                ('uchrashuv_sana', models.DateField(blank=True, null=True, verbose_name="Uchrashuv o'tkazilgan sana")),
                ('uchrashuvda_qatnashgan', models.BooleanField(default=False, verbose_name="Uchrashuv o'tkazilgan")),
                ('xizmat_sana', models.DateField(blank=True, null=True, verbose_name="Xizmat ko'rsatilgan sana")),
                ('xizmat_korsatilgan', models.BooleanField(default=False, verbose_name="Xizmat ko'rsatilgan")),
                ('boshqa_muammo_izohi', models.CharField(blank=True, max_length=500, verbose_name='Boshqa muammo (izoh)')),
                ('muammo_aniqlanmagan', models.BooleanField(default=False, verbose_name='Uchrashuvda muammo aniqlanmagan')),
                ('kerakli_xizmatlar_soni', models.PositiveSmallIntegerField(default=0, verbose_name='Kerakli xizmatlar soni')),
                ('korsatilgan_xizmatlar_soni', models.PositiveSmallIntegerField(default=0, verbose_name="Ko'rsatilgan xizmatlar soni")),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('ijtimoiy_toifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shaxslar', to='registry.ijtimoiytoifa', verbose_name='Ijtimoiy reestrdagi toifasi')),
                ('mahalla', models.ForeignKey(help_text='Oilaning mahallasi; filtrlashni tezlashtirish uchun takrorlanadi', on_delete=django.db.models.deletion.CASCADE, related_name='shaxslar', to='registry.mahalla', verbose_name='Mahalla')),
                ('muammo_toifasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shaxslar', to='registry.muammotoifasi', verbose_name='Izoh (muammo toifasi)')),
                ('oila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azolar', to='registry.oila', verbose_name='Oila')),
            ],
            options={
                'verbose_name': 'Shaxs',
                'verbose_name_plural': 'Shaxslar',
                'ordering': ['oila__unikal_id', '-asosiy_arizachi', 'fio'],
            },
        ),
        migrations.CreateModel(
            name='ShaxsIjtimoiyHolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaxs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ijtimoiy_holatlari', to='registry.shaxs', verbose_name='Shaxs')),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shaxslar', to='registry.ijtimoiyholatturi', verbose_name='Ijtimoiy holat turi')),
            ],
            options={
                'verbose_name': 'Shaxsning ijtimoiy holati',
                'verbose_name_plural': 'Shaxslarning ijtimoiy holatlari',
                'ordering': ['turi__tartib'],
            },
        ),
        migrations.CreateModel(
            name='XizmatTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.SlugField(max_length=64, unique=True, verbose_name='Kod')),
                ('nomi', models.CharField(max_length=255, verbose_name='Xizmat nomi')),
                ('nomi_kiril', models.CharField(blank=True, max_length=255, verbose_name='Xizmat nomi (kirill)')),
                ('summasi_bor', models.BooleanField(default=False, help_text="Manba faylda bu xizmat uchun mln so'mdagi summa ustuni bor", verbose_name="Summa ko'rsatiladi")),
                ('tartib', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('ota_turi', models.ForeignKey(blank=True, help_text="Masalan, 'Yoshlar daftaridan' - 'Ijtimoiy daftarlar'ning quyi turi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quyi_turlari', to='registry.xizmatturi', verbose_name='Yuqori turdagi xizmat')),
            ],
            options={
                'verbose_name': 'Xizmat turi',
                'verbose_name_plural': 'Xizmat turlari',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('kerakli', "Kerak bo'lgan (xatlov holati)"), ('korsatilgan', "Ko'rsatilgan (ijro holati)")], db_index=True, max_length=12, verbose_name='Holat')),
                ('soni', models.PositiveSmallIntegerField(default=1, verbose_name='Soni')),
                ('summa_mln', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name="Summa (mln so'm)")),
                ('shaxs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xizmatlar', to='registry.shaxs', verbose_name='Shaxs')),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xizmatlar', to='registry.xizmatturi', verbose_name='Xizmat turi')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['turi__tartib'],
            },
        ),
        migrations.AddIndex(
            model_name='shaxs',
            index=models.Index(fields=['mahalla', 'jinsi'], name='registry_sh_mahalla_3e7e98_idx'),
        ),
        migrations.AddIndex(
            model_name='shaxs',
            index=models.Index(fields=['mahalla', 'ijtimoiy_toifa'], name='registry_sh_mahalla_459bf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='shaxsijtimoiyholat',
            constraint=models.UniqueConstraint(fields=('shaxs', 'turi'), name='ijtimoiy_holat_shaxs_turi'),
        ),
        migrations.AddConstraint(
            model_name='xizmat',
            constraint=models.UniqueConstraint(fields=('shaxs', 'turi', 'holat'), name='xizmat_shaxs_turi_holat'),
        ),
    ]
