# Generated by Django 5.0.14 on 2026-09-17 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hudud', models.CharField(max_length=255, verbose_name='Hudud (tuman/shahar)')),
                ('nomi', models.CharField(max_length=255, verbose_name='MFY nomi')),
                ('kodi', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='MFY kodi')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
                'ordering': ['hudud', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Oila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oila_unikal_id', models.CharField(db_index=True, max_length=64, verbose_name='Oila unikal ID')),
                ('oila_azolari_soni', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Oila a'zolari soni")),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilalar', to='registry.mahalla', verbose_name='Mahalla')),
            ],
            options={
                'verbose_name': 'Oila',
                'verbose_name_plural': 'Oilalar',
                'unique_together': {('mahalla', 'oila_unikal_id')},
            },
        ),
        migrations.CreateModel(
            name='Shaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib_raqami', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tartib raqami')),
                ('asosiy_arizachi', models.BooleanField(default=False, verbose_name='Asosiy arizachi')),
                ('jshshir', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='JSHSHIR')),
                ('fio', models.CharField(db_index=True, max_length=255, verbose_name='F.I.O.')),
                ('jinsi', models.CharField(blank=True, choices=[('Эркак', 'Erkak'), ('Аёл', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('tugilgan_sana', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('yoshi', models.FloatField(blank=True, null=True, verbose_name='Yoshi')),
                ('ijtimoiy_toifa', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Ijtimoiy reestrdagi toifasi')),
                ('izoh', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('reestrdan_chiqqan', models.BooleanField(default=False, verbose_name="O'z arizasiga ko'ra ijtimoiy reestrdan chiqqan")),
                ('uchrashuv_sana', models.DateField(blank=True, null=True, verbose_name="Uchrashuv o'tkazilgan sana")),
                ('uchrashuv_qatnashgan', models.BooleanField(default=False, verbose_name='Uchrashuvda qatnashgan')),
                ('xizmat_sana', models.DateField(blank=True, null=True, verbose_name="Xizmat ko'rsatilgan sana")),
                ('xizmat_qatnashgan', models.BooleanField(default=False, verbose_name="Xizmat ko'rsatilgan")),
                ('kerakli_xizmatlar', models.JSONField(blank=True, default=dict, verbose_name='Kerakli xizmatlar')),
                ('boshqa_muammo', models.JSONField(blank=True, default=dict, verbose_name='Boshqa muammo belgilari')),
                ('korsatilgan_xizmatlar', models.JSONField(blank=True, default=dict, verbose_name="Ko'rsatilgan xizmatlar")),
                ('ijtimoiy_holat_belgilari', models.JSONField(blank=True, default=dict, verbose_name='Ijtimoiy holat belgilari')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('oila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azolar', to='registry.oila', verbose_name='Oila')),
            ],
            options={
                'verbose_name': 'Shaxs',
                'verbose_name_plural': 'Shaxslar',
                'ordering': ['oila', 'tartib_raqami'],
            },
        ),
    ]
