# Generated by Django 5.0.14 on 2026-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaxs',
            name='ijtimoiy_holatlar',
            field=models.ManyToManyField(blank=True, related_name='belgilangan_shaxslar', through='registry.ShaxsIjtimoiyHolat', to='registry.ijtimoiyholatturi', verbose_name='Ijtimoiy holat belgilari'),
        ),
    ]
