# Generated by Django 5.0.14 on 2026-09-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_shaxs_ijtimoiy_holatlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MurojaatSababi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, unique=True, verbose_name='Murojaat sababi')),
                ('tavsifi', models.CharField(blank=True, max_length=500, verbose_name='Qisqa tavsif')),
                ('tartib', models.PositiveSmallIntegerField(default=100, help_text="Ro'yxatda kichik raqam yuqorida turadi", verbose_name='Tartib')),
                ('faol', models.BooleanField(default=True, help_text="Belgi olinsa, yangi yozuvlarda tanlash uchun ko'rinmaydi", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Murojaat sababi',
                'verbose_name_plural': 'Murojaat sabablari',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.AddField(
            model_name='shaxs',
            name='murojaat_izohi',
            field=models.TextField(blank=True, help_text='Murojaat mazmuni erkin shaklda (ixtiyoriy)', verbose_name='Murojaat izohi'),
        ),
        migrations.AddField(
            model_name='shaxs',
            name='murojaat_sababi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shaxslar', to='registry.murojaatsababi', verbose_name='Nima uchun murojaat qilgan'),
        ),
    ]
